title: Developer
subtitle: HighOnCode || Machine Learning || Deep Learning || Contributor
description: >- # this means to ignore newlines until "baseurl
  Hi guys , I am Satyam Kumar Yadav .

url: "https://satyam-kumar-yadav.github.io"
baseurl: "" # the subpath of your site, e.g. /blog

urls:
  - text: About Me
    url: /about
  - text: Projects
    url: /shop
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery
  - text: Contact Me
    url: /contact
  # - text: Styleguide
  #   url: /styleguide
  # - text: Get Started
  #   url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Satyam Kumar Yadav
author_bio:
  Hey, this is about me, so I have to say something about myself. Sometimes it is hard to introduce yourself because you know yourself so well that you do not know where to start with. Let me give a try to see what kind of image you have about me through my self-description. I hope that my impression about myself and your impression about me are not so different. Here it goes.
  I am a person who is positive about every aspect of life. There are many things I like to do, to see, and to experience. I like to read, I like to write; I like to think, I like to dream; I like to talk, I like to listen. I like to feel the music flowing on my face. I like to look at the clouds in the sky with a blank mind, I like to do thought experiment when I cannot sleep in the middle of the night. I like to sleep early, I like to get up late; I like to be alone, I like to be surrounded by people. I like country’s peace, I like metropolis’ noise. I like delicious food and comfortable shoes; I like good books and romantic movies. I like the land and the nature, I like people. And, I like to laugh.
author_email: "satyamyadav6119@gmail.com"
author_location: India
typewrite-text: I allow myself to forgive; it will allow me to move beyond the pain, to a place of peace.
written : I have seen an acceleration in my learning curve, a deeper understanding of statistics and python, and a large improvement in my communication skills since starting my blog. I never realized how useful maintaining a blog could be as a learning technique. This comes with the added benefit of being able to store information and code for myself and for others to also use, which is essential for getting feedback and connecting with other people.
# Experiences
author_work_experiences:
  - company_name: KPMG
    company_logo: google.png
    company_url: https://home.kpmg/xx/en/home.html
    designation: Data Analytics Consulting Virtual Internship
    description: Worked on various Data Quality Assessment , Data Insight , Data Insight and Presentation
    visibility: true
  - company_name: Quantium
    company_logo: quantium.png
    company_url: https://quantium.com/
    designation: Data Analytics Consulting Virtual Internship
    description: Worked on various Data Quality Assessment , Data Insight , Data Insight and Presentation
    visibility: true

# Education
author_education_details:
  - college_logo: IITBHU-Logo.jpg
    college_name: IIT BHU
    college_url: https://iitbhu.ac.in
    college_degree: Bachelor of Technology
    visibility: true
  - college_logo: thecoding.png
    college_name: The Coding School
    college_url: https://codeconnects.org/
    college_degree: Quantum Computing
    visibility: true
# Projects
author_project_details:
  - project_thumbnail: waveform.png
    project_title: Song generation
    project_description: I train the Recurrent Neural Network (RNN) for music generation.
    project_url: https://github.com/Satyam-kumar-yadav/Machine_sings
    visibility: true
  - project_thumbnail: price.jpg
    project_title: Price Prediction
    project_description: This is Hacker Earth Machine Learning competition.
    project_url: https://github.com/Satyam-kumar-yadav/Price_Prediction
    visibility: true

# social links
twitter_username: SatyamK10679747
github_username: Satyam-kumar-yadav
facebook_username: satyamkumar.yadav.7906
linkedin_username: satyamkryadav
instagram_username: satyam_kr_yadav
medium_username: satyamkumaryadav

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )
formspree_email: f/mleopzqd
# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 2648

# wakatime username (coding activity)
wakatime_username: Satyam Kumar Yadav

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  - scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  - scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
